### ISSUE TITLE
Configure CI/CD Pipeline on Cloud Server for Each Individual App

### ISSUE THREAD

**Issue by gaberch** [ece651-winter2019/ece651-group-project#39]
Target:

- Successful build and deployment of pyramid web framework application
- Successful build and deployment of mobile application

**Comment by phoenixtype** [comment]
The build of pyramid web framework application for the progress so far worked, however there is an error message while using gradle to build the mobile application. Also, there is a challenge in configuring the YAML file to build simultaneously for different platforms in the same repository. Please refer to this status badges for details of the build.
 
[![Build Status](https://dev.azure.com/Akumasamuel1/ProjectHMS/_apis/build/status/ProjectHMS-Gradle-CI%20(2)?branchName=master)](https://dev.azure.com/Akumasamuel1/ProjectHMS/_build/latest?definitionId=42&branchName=master)

[![Build Status](https://dev.azure.com/Akumasamuel1/ProjectHMS/_apis/build/status/ProjectHMS-Python%20package-CI%20(2)?branchName=master)](https://dev.azure.com/Akumasamuel1/ProjectHMS/_build/latest?definitionId=33&branchName=master)
