### ISSUE TITLE
Can't commit changes to my branch

### ISSUE THREAD

**Issue by ammarahmed93** [ece651-winter2019/ece651-group-project#78]
<img width="1051" alt="Screen Shot 2019-03-12 at 8 52 29 PM" src="https://user-images.githubusercontent.com/43079200/54245812-c34a6b80-4508-11e9-9107-7bc1d96d5a09.png">

**Comment by adkulas** [comment]
Quick and dirty solution:
use `SKIP=wily` before your git commands:
example: `SKIP=wily git commit -m "stuff"`

long answer:
wily needs to build the cache so use `pipenv run wily healthapp_project/healapp_root`
then you should be able to pre-commit with wily

**Comment by ammarahmed93** [comment]
Thanks!
