### ISSUE TITLE
API to communicate to backend

### ISSUE THREAD

**Issue by adkulas** [ece651-winter2019/ece651-group-project#8]
Need to determine how to interface with the backend
Based on our meeting we are leaning towards a REST api using JSON file format

Possible solution?
https://github.com/encode/apistar

Maybe start googling "how to make an api"

**Comment by gaberch** [comment]
[API Research.docx](https://github.com/adkulas/ece651-group-project/files/2798129/API.Research.docx)

Some research I did to better understand APIs, difference between REST and SOAP as well as difference between XML and JSON file formats.

Important Note: If we're looking to go with MySQL for the database, we must confirm that it is compatible with JSON file formats. My research suggests that MySQL databases don't support JSON file formats.

**Comment by adkulas** [comment]
Here is a tutorial and example project using ramses and RAML to define an api
https://realpython.com/create-a-rest-api-in-minutes-with-pyramid-and-ramses/

**Comment by adkulas** [comment]
duplicate #57
