### ISSUE TITLE
Need API to query patient records based on given time interval

### ISSUE THREAD

**Issue by gaberch** [ece651-winter2019/ece651-group-project#83]
Create an API that returns patient record based on input consisting of a time interval. User must be authenticated and have appropriate permissions to be able to do this.

**Comment by adkulas** [comment]
@gaberch I found some documentation on this in djangorestframework
https://www.django-rest-framework.org/api-guide/filtering/

Theres an extension package that give ability to query through the browsable api
https://www.django-rest-framework.org/api-guide/filtering/#generic-filtering

we would need to `pip install django-filter` and add it to the settings.py as an app

**Comment by gaberch** [comment]
Token providing API created based based on provided username and password:
Path of Token Providing API: /api/token-auth
Post Request format:
{
"username":<insert user name>,
"password":<insert password>
}

Response:
{
"token": "..."
}

Mobile User must store Token ID on device and use this token as part of data request in order to be authenticated

**Comment by gaberch** [comment]
Closed by branch finalize-api-functionality
