### ISSUE TITLE
APIs currently not working with Mobile Front End

### ISSUE THREAD

**Issue by gaberch** [ece651-winter2019/ece651-group-project#84]

**Comment by adkulas** [comment]
I was able to `POST` data at the url https://pyramid-backend.herokuapp.com/api/patientrecords
the body of the data was 
```json
[    
    {
        "user": 222,
        "bp_diastolic": 70,
        "bp_systolic": 165,
        "created_on": 1456,
        "heart_rate": 60,
        "weight": 180,
        "height": 183
    }
]
```

**Comment by adkulas** [comment]
If you query you get the same data back

**Comment by gaberch** [comment]
@torontotong let me know if you still have issues based on the above info

**Comment by torontotong** [comment]
Verified with the mobile application,  issue resolved.

**Comment by gaberch** [comment]
@torontotong You no longer need to add the field "created_on". It is automatically set to the current date and time
Post request will now be as follows:
[    
    {
        "user": 222,
        "bp_diastolic": 71,
        "bp_systolic": 120,
        "heart_rate": 61,
        "weight": 180,
        "height": 183
    },
    {
        "user": 222,
        "bp_diastolic": 72,
        "bp_systolic": 111,
        "heart_rate": 62,
        "weight": 180,
        "height": 183
    },
    {
        "user": 222,
        "bp_diastolic": 80,
        "bp_systolic": 120,
        "heart_rate": 68,
        "weight": 180,
        "height": 183
    }
]
