### ISSUE TITLE
Web App Doctor Dashboard Needs Backend Functionality for Querying Individual Patient Records for Doctor Dashboard

### ISSUE THREAD

**Issue by gaberch** [ece651-winter2019/ece651-group-project#93]
- Need Backend Functionality to automatically query and return appropriate patient record when Doctor clicks the "View Records" button for a patient

- Button to bring doctor user to a new HTML page

**Comment by jmcarrillog** [comment]
Thanks Gabe, I am working on this.

**Comment by gaberch** [comment]
Awesome, glad that you're working on this too. I'm working on the server side connections to provide you the dictionaries you need to render. I'll split this into two issues. One for frontend and one for backend
