### ISSUE TITLE
Patient Sign Up Form Currently Asks Patient User for Doctor ID 

### ISSUE THREAD

**Issue by gaberch** [ece651-winter2019/ece651-group-project#99]
Need to modify this to select from a drop down list of available doctors. List should display names of doctors.

**Comment by jmcarrillog** [comment]
Just out of curiosity, is this issue related to some of the priority features listed in the [requirements](https://github.com/ece651-winter2019/ece651-group-project/wiki/1-Requirements-Specification)? Are the patients able to sign-up using the app? I thought they were only going to log in using credentials assigned by the sysadmin.

**Comment by gaberch** [comment]
Yes if the patient user does not have the doctor ID to sign up. Without it, they are unable to create an account. We can assume that the patient user will be provided this information prior to sign up and maybe make this issue a low priority
